spring:
  application:
    name: RedisApp
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: postgres
  jpa:
    show-sql: true
  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6379

security:
  jwt:
    secret-key: 9b5167a3340fc7adc3937c19cac50aba15bf16bee615b997468809216a388068
    expiration-time: 3600000 # in milliseconds
